language: csharp

reviews:
  profile: assertive   # balanced | assertive | chill
  high_level_summary: true
  review_status: true

  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "draft"

  path_filters:
    - "!**/bin/**"
    - "!**/obj/**"
    - "!**/*.Designer.cs"
    - "!**/Migrations/**"

coding_guidelines:
  - Follow C# naming conventions
  - Prefer async/await over Task.Result or .Wait()
  - Avoid blocking calls in ASP.NET
  - Use Dependency Injection properly
  - Validate DTOs and user inputs
  - Avoid magic strings and numbers

security:
  enabled: true

performance:
  enabled: true
